#  Local setting valid for only this environment
api_gateway_username: admin
api_gateway_password: changeme
api_portal__username: apiadmin
api_portal__password: changeme

gateway_lisence_name: apiGateway.lic
manager_lisence_name: apiMgr.lic

localCertUrl: https://localhost:8090
# Envsettings.props fields with overrides
# Chache rmiURL

# Analytics Database properties
analytics_dburl: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=arac01-scan.test.sparebank1.no)(PORT=1521))(LOAD_BALANCE=YES)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=svc_kunde_axway)))
analytics_dbuser: apigw
analytics_dbpassword: apigw

# API Gateway sb1sk- services username and password
gateway_sb1sk_username: apigateway
gateway_sb1sk_password: Qwer1234!

# API Gateway esb - services username and password
gateway_esb_username: webapi_axway_api_gw
gateway_esb_password: VM257HE1

# Whitelist for CSRF protection, primarily for allowing a load balancer
csrf_whitelist: '^https?:\/\/api-manager\.test\.sparebank1\.no'

# Integration URLs
stage: test
sb1sk_basepath: 'https://sb1skws.test.sparebank1.no:443'
apiautorisasjon_basepath: 'https://api-authorization-internal.test.sparebank1.no'
difi_basepath: 'https://oidc-ver2.difi.no'

# Used by ldap autentication in API-Manager
apimanager_ad_admin_role: 'CN=Role-Prosjekt-Apne-Api-NSA,OU=Roles,OU=Groups,OU=NSA,OU=Customers,DC=sb1a,DC=sparebank1,DC=no'

# Global HTTP header incoming whitelist
incoming_whitelist: Accept,Accept-Charset,Accept-Encoding,Accept-Language,Accept-Datetime,Authorization,Cache-Control,Connection,Cookie,Content-Length,Content-Type,Date,Forwarded,From,Host,Location,Origin,Pragma,Referer,User-Agent,Upgrade,Via,Warning,X-Forwarded-For,X-Forwarded-Host,X-Forwarded-Proto,AppKey,sst,rmt,financial_institution_id,financial_agreement_id,useAutomaticConsentScreen,ssn,rmt_expiration_date_time,agreement_ids,PartyID,Legal-Mandate,CorrelationID,AccountID,authorization,userinfo,X-Request-Id,X-Request-ID,X-User-Id,X-nonce,X-dynamicLinkingStamp,X-authmethod,X-clientIpAddress,X-bankRegNumber,X-idpType,customerID,AccountInfoRequestID

# Global HTTP header outgoing whitelist
outgoing_whitelist: Access-Control-Allow-Origin,Accept-Patch,Accept-Ranges,Allow,Alt-Svc,Cache-Control,Connection,Content-Disposition,Content-Encoding,Content-Language,Content-Length,Content-Location,Content-Range,Content-Type,Date,ETag,Expires,Last-Modified,Link,Location,Pragma,Proxy-Authenticate,Public-Key-Pins,Refresh,Retry-After,Server,Set-Cookie,Status,Strict-Transport-Security,Trailer,Transfer-Encoding,TSV,Upgrade,Vary,WarnJaing,WWW-Authenticate,X-Correlation-ID,ConsentScreen,Status,X-Request-Id,X-Request-ID,X-User-Id,X-nonce,X-dynamicLinkingStamp,X-authmethod,X-clientIpAddress,X-bankRegNumber,numberOfPages,audience,AccountInfoRequestID

# cassandra keyspace
cassandra_keyspace: evil_corp

# cassandra hosts (is not overriden  is done based on which group the server belongs to )

### PSD2 settings
issuer: 'https://api-test.sparebank1.no'
# claim iss
token_lifespan: 240
# claim exp + iat (in secounds)
psd2_token_audience: 'evry-psd2-platform'

# Filebeat
filebeat_username: gOy2kORDtU6QmPxQho0P9SqdsGgvUB3S61m3TzpcnK1J
