---
# ==========================================================================================
- name: Template loadCerts.sh.j2
  template:
    src: ../templates/loadCerts.sh.j2
    dest: "{{ path_update }}/loadCerts.sh"
    owner: "{{ appRunUser }}"
    mode: '0777'

# ==========================================================================================
- name: Update lokal certs-> "{{ path_update }}/loadCerts.sh"
  command: "{{ path_update }}/loadCerts.sh"
  become_user: "{{ appRunUser }}"
  register: output

- name: Output from load sertificates.
  debug:
    msg: "{{ output }}"
