#  Local setting valid for only this environment
api_gateway_username: "admin"
api_gateway_password: "changeme"
api_portal_username: "apiadmin"
api_portal_password: "changeme"

zabbixServerGroupDesc: apigw-admin03.prod, apigw-admin04.prod, apigw03.prod og apigw04.prod
displayAnsibleMessages: true

gateway_lisence_name: apiGateway.lic
manager_lisence_name: apiMgr.lic

localCertUrl: https://localhost:8090

# API Gateway xx1sk- services username and password
gateway_xx1sk_username: "apigateway"
gateway_xx1sk_password: "changeme"

# Whitelist for CSRF protection, primarily for allowing a load balancer
csrf_whitelist: '^https?:\/\/api-manager\.prod\.customer\.no'

# Integration URLs
stage: prod
# Used by ldap autentication in API-Manager
apimanager_ad_admin_role: "CN=Role-Axway-Api-Manager-NSA,OU=Roles,OU=Groups,OU=NSA,OU=Customers,DC=xx1a,DC=customer,DC=no"

# cassandra keyspace
cassandra_keyspace: apigw_77
cassandra_keyspace_77: apigw_77

# cassandra hosts (is not overriden  is done based on which group the server belongs to )

### PSD2 settings
issuer: "https://api-prod.customer.no"
# claim iss
token_lifespan: 240
# claim exp + iat (in secounds)
psd2_token_audience: 'evry-psd2-platform'

# Filebeat
filebeat_username: xxxx

cassandra_cluster_name: API GW PROD