#  Local setting valid for only this environment
api_gateway_username: "admin"
api_gateway_password: "changeme"
api_portal_username: "apiadmin"
api_portal_password: "changeme"

zabbixServerGroupDesc: apigw-admin03.qa, apigw-admin04.qa, apigw03.qa og apigw04.qa
displayAnsibleMessages: true

gateway_lisence_name: apiGateway.lic
manager_lisence_name: apiMgr.lic

localCertUrl: https://localhost:8090

# Whitelist for CSRF protection, primarily for allowing a load balancer
csrf_whitelist: '^https?:\/\/api-manager\.qa\.customer\.no'

# Integration URLs
stage: qa

# Used by ldap autentication in API-Manager
apimanager_ad_admin_role: "CN=Role-Prosjekt-Apne-Api-NSA,OU=Roles,OU=Groups,OU=NSA,OU=Customers,DC=xx1a,DC=customer,DC=no"

# cassandra keyspace
cassandra_keyspace: "x8b2a57ef_feb0_4c5a_a72b_ac2e9825092d_group_2"
cassandra_keyspace_77: apigw_77
# cassandra hosts (is not overriden  is done based on which group the server belongs to )

### PSD2 settings
issuer: "https://api.qa.customer.no"
# claim iss
token_lifespan: 240
# claim exp + iat (in secounds)
psd2_token_audience: 'evry-psd2-platform'

# Filebeat
filebeat_username: "changeme"

cassandra_cluster_name: API GW QA 