#  Local setting valid for only this environment
api_gateway_username: admin
api_gateway_password: changeme
api_portal_username: apiadmin
api_portal_password: changeme
api_rnm_password: changeme

zabbixServerGroupDesc: apigw-admin01.test, apigw-admin02.test, apigw01.test og apigw02.test
displayAnsibleMessages: false

gateway_lisence_name: apiGateway.lic
manager_lisence_name: apiMgr.lic

localCertUrl: https://localhost:8090
# Whitelist for CSRF protection, primarily for allowing a load balancer
csrf_whitelist: '^https?:\/\/api-manager\.test\.customer\.no'

# Integration URLs
stage: test

# Used by ldap autentication in API-Manager
apimanager_ad_admin_role: 'CN=Role-Prosjekt-Apne-Api-NSA,OU=Roles,OU=Groups,OU=NSA,OU=Customers,DC=xx1a,DC=customer,DC=no'

# cassandra keyspace
cassandra_keyspace: evil_corp

cassandra01: apigw-cass01
cassandra02: apigw-cass02
cassandra03: apigw-cass03
cassandra04: apigw-cass04
cassandra05: apigw-cass05
cassandra06: apigw-cass06

cassandra_cluster_name: API GW TEST

### PSD2 settings
issuer: 'https://api-test.customer.no'
# claim iss
token_lifespan: 240
# claim exp + iat (in secounds)
psd2_token_audience: 'evry-psd2-platform'

# Filebeat
filebeat_username: changeme
