#  Local setting valid for only this environment
api_gateway_username: admin
api_gateway_password: changeme
api_portal_username: apiadmin
api_portal_password: changeme

zabbixServerGroupDesc: apigw-admin01.test, apigw-admin02.test, apigw01.test og apigw02.test
displayAnsibleMessages: false

gateway_lisence_name: apiGateway.lic
manager_lisence_name: apiMgr.lic

localCertUrl: https://localhost:8090
# Envsettings.props fields with overrides
# Chache rmiURL

# Analytics Database properties
analytics_dburl: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=arac01-scan.test.sparebank1.no)(PORT=1521))(LOAD_BALANCE=YES)(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=svc_kunde_axway)))
analytics_dbuser: apigw
analytics_dbpassword: apigw

# API Gateway sb1sk- services username and password
gateway_sb1sk_username: apigateway
gateway_sb1sk_password: Qwer1234!

# API Gateway esb - services username and password
gateway_esb_username: webapi_axway_api_gw
gateway_esb_password: VM257HE1

# Whitelist for CSRF protection, primarily for allowing a load balancer
csrf_whitelist: '^https?:\/\/api-manager\.test\.sparebank1\.no'

# Integration URLs
stage: test
sb1sk_basepath: 'https://sb1skws.test.sparebank1.no:443'
apiautorisasjon_basepath: 'https://api-authorization-internal.test.sparebank1.no'
difi_basepath: 'https://oidc-ver2.difi.no'
maskinporten_basepath: 'https://ver2.maskinporten.no'

# Used by ldap autentication in API-Manager
apimanager_ad_admin_role: 'CN=Role-Prosjekt-Apne-Api-NSA,OU=Roles,OU=Groups,OU=NSA,OU=Customers,DC=sb1a,DC=sparebank1,DC=no'

# cassandra keyspace
cassandra_keyspace: evil_corp
cassandra_main_server: apigw-cass01.test.sparebank1.no

# cassandra hosts (is not overriden  is done based on which group the server belongs to )

### PSD2 settings
issuer: 'https://api-test.sparebank1.no'
# claim iss
token_lifespan: 240
# claim exp + iat (in secounds)
psd2_token_audience: 'evry-psd2-platform'

# Filebeat
filebeat_username: gOy2kORDtU6QmPxQho0P9SqdsGgvUB3S61m3TzpcnK1J
