#  Local setting valid for only this environment
api_gateway_username: admin
api_gateway_password: changeme
api_portal_username: apiadmin
api_portal_password: N0rgesBesteDigitalBank!
api_rnm_password: changeme

zabbixServerGroupDesc: apigw-admin01.test, apigw-admin02.test, apigw01.test og apigw02.test
displayAnsibleMessages: false

gateway_lisence_name: apiGateway.lic
manager_lisence_name: apiMgr.lic

localCertUrl: https://localhost:8090
# Envsettings.props fields with overrides
# Chache rmiURL

# API Gateway xx1sk- services username and password
gateway_xx1sk_username: apigateway
gateway_xx1sk_password: Qwer1234!

# API Gateway esb - services username and password
gateway_esb_username: webapi_axway_api_gw
gateway_esb_password: VM257HE1

# Whitelist for CSRF protection, primarily for allowing a load balancer
csrf_whitelist: '^https?:\/\/api-manager\.test\.customer\.no'

# Integration URLs
stage: test
xx1sk_basepath: 'https://xx1skws.test.customer.no:443'
apiautorisasjon_basepath: 'https://internal-api-backend.test.customer.no'
difi_basepath: 'https://oidc-ver2.difi.no'
maskinporten_basepath: 'https://ver2.maskinporten.no'

# Used by ldap autentication in API-Manager
apimanager_ad_admin_role: 'CN=Role-Prosjekt-Apne-Api-NSA,OU=Roles,OU=Groups,OU=NSA,OU=Customers,DC=xx1a,DC=customer,DC=no'

# cassandra keyspace
cassandra_keyspace: evil_corp

cassandra01: apigw-cass01
cassandra02: apigw-cass02
cassandra03: apigw-cass03
cassandra04: apigw-cass04
cassandra05: apigw-cass05
cassandra06: apigw-cass06

cassandra_cluster_name: API GW TEST

# cassandra_main_server: apigw-cass01.test.customer.no

# cassandra hosts (is not overriden  is done based on which group the server belongs to )
### PSD2 settings
issuer: 'https://api-test.customer.no'
# claim iss
token_lifespan: 240
# claim exp + iat (in secounds)
psd2_token_audience: 'evry-psd2-platform'

# Filebeat
filebeat_username: gOy2kORDtU6QmPxQho0P9SqdsGgvUB3S61m3TzpcnK1J

# HAP verdier brukt av selvbetjening
hap_hosts:
  - hap-test03.test.customer.no
  - hap-test04.test.customer.no
hap_backends:
  - api_manager_backend
  - api_manager_http_backend
  - apigw_manager_backend

# lokale variable relatert til sletting av rmt fra cassandra
apigw_admin: apigw-admin01.test.customer.no
apigwBasePath: https://{{ apigw_admin }}/api/router/service/
apigwInstance: instance-1
