---
# ==========================================================================================
- name: Copy install file og script
  copy:
    src: "{{ item }}"
    dest: "{{ path_update }}"
    mode: '0777'
  become_user: "{{ appRunUser }}"
  with_fileglob:
     - files/*.sh

- name: Set variable for gr1
  set_fact:
     cassandra_env01: "{{cassandra01}}"
     cassandra_env02: "{{cassandra03}}"
     cassandra_env03: "{{cassandra05}}"
  when: gateway_group_name == "gr1"

- name: Set variable for gr2
  set_fact:
     cassandra_env01: "{{cassandra02}}"
     cassandra_env02: "{{cassandra04}}"
     cassandra_env03: "{{cassandra06}}"
  when: gateway_group_name == "gr2"

- name: Template a file to {{ path_update }}/envSettings.props
  template:
    src: ./template/envSettings.props.j2
    dest: "{{ path_update }}/envSettings.props"
    owner: "{{ appRunUser }}"
    group: wheel
    mode: '0644'

# - name: Copy envSettings to instance - config
- name: Copy command -> ({{ appRunUser }}) "{{ path_update }}/copyEnvSettings.sh {{ gateway_group_name }} {{ path_update }} {{ api_gateway_home }} {{ hostnameShort }}"
  command: "{{ path_update }}/copyEnvSettings.sh {{ gateway_group_name }} {{ path_update }} {{ api_gateway_home }} {{ hostnameShort }}"
  become_user: "{{ appRunUser }}"
  register: standard_output
  args:
      chdir: "{{ path_update }}"

- debug:
      var: standard_output.stdout_lines
