prod:
  children:
    servers:
      children:
        adminServers:
          hosts:
            apigw-admin03.prod.sparebank1.no:
              axwaytype: domainAdmin
              hostnameShort: apigw-admin03
              anmHost:
              gateway_group_name: gr1
              rmi_peer: apigw-admin04.prod.sparebank1.no:40001
              hap_srvnavn: apigw-admin03
              rmisrv: localhost
            apigw-admin04.prod.sparebank1.no:
              axwaytype: admin
              hostnameShort: apigw-admin04
              anmHost: apigw-admin03.prod.sparebank1.no
              gateway_group_name: gr2
              rmi_peer: apigw-admin03.prod.sparebank1.no:40001
              hap_srvnavn: apigw-admin04
              rmisrv: localhost
        gatewayServers:
          hosts:
            apigw03.prod.sparebank1.no:
              axwaytype: admin
              hostnameShort: apigw03
              anmHost: apigw-admin03.prod.sparebank1.no
              gateway_group_name: gr1
              rmi_peer: apigw04.prod.sparebank1.no:40001
              hap_srvnavn: apigw03
              rmisrv: apigw04.prod.sparebank1.no
            apigw04.prod.sparebank1.no:
              axwaytype: admin
              hostnameShort: apigw04
              anmHost: apigw-admin04.prod.sparebank1.no
              gateway_group_name: gr2
              rmi_peer: apigw03.prod.sparebank1.no:40001
              hap_srvnavn: apigw04
              rmisrv: apigw03.prod.sparebank1.no
        allServers:
          hosts:
            apigw-admin03.prod.sparebank1.no:
              axwaytype: admin
        cassandraServers:
          hosts:
            apigw-cass01.prod.sparebank1.no:
            apigw-cass02.prod.sparebank1.no:
            apigw-cass03.prod.sparebank1.no:
            apigw-cass04.prod.sparebank1.no:
            apigw-cass05.prod.sparebank1.no:
            apigw-cass06.prod.sparebank1.no:
